version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./company_dataset.json:/app/../company_dataset.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/ai-prospecting
      - NODE_OPTIONS=--max-old-space-size=8192
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ai-prospecting
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    command: ["--wiredTigerCacheSizeGB", "2"]

volumes:
  mongodb-data:
    driver: local 