version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ai-prospecting-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ai-prospecting

volumes:
  mongodb-data: 